# Generated by Django 2.1.5 on 2019-02-08 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('media_url', models.CharField(max_length=1000, null=True)),
                ('contain_media', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likers', models.ManyToManyField(related_name='article_likers', to=settings.AUTH_USER_MODEL)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posted article',
                'ordering': ['timestamp', 'title'],
                'verbose_name_plural': 'Posted article list',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=100)),
                ('user_username', models.CharField(max_length=100)),
                ('article_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Posted comment',
                'ordering': ['user_instance__username'],
                'verbose_name_plural': 'Posted comment list',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LIKE', 'Liked'), ('COMMENT', 'Commented')], max_length=10)),
                ('article_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedapp.Article')),
                ('engager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['user_instance__username'],
                'verbose_name_plural': 'Notification list',
            },
        ),
    ]
